services:
  - type: web
    name: masjide-abubakr
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: flask run --host=0.0.0.0 --port=10000
    autoDeploy: true
    envVars:
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: development
      - key: PORT
        value: 10000
